services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python waitress_server.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"